version: '3'

silent: true

tasks:

  build:
    desc: Builds in debug mode
    cmds:
      - cmd: cargo +stable build

  clean:
    desc: Cleans all targets
    cmds:

  clippy:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo +stable clippy --all-targets
      - cmd: cargo +stable clean

  cov:
    desc: Generates code coverage report in text format
    cmds:
      - cmd: cargo +stable llvm-cov clean
      - cmd: cargo +stable llvm-cov --no-cfg-coverage

  cov-html:
    desc: Generates code coverage report in HTML format
    cmds:
      - cmd: cargo +stable llvm-cov clean
      - cmd: cargo +stable llvm-cov --no-cfg-coverage --html --open

  cov-badge:
    desc: Generates the detailed code coverage badge
    cmds:
      - cmd: cargo +stable llvm-cov clean
      - cmd: cargo +stable llvm-cov --no-cfg-coverage --json --summary-only | coverio --collapse --tag cov-badge-wasmarin

  doc:
    desc: Generates documentation
    cmds:
      - cmd: cargo +stable doc

  doc-private:
    desc: Generates documentation
    cmds:
      - cmd: cargo +stable doc --document-private-items

  doc-open:
    desc: Generates documentation and opens in browser
    cmds:
      - cmd: cargo +stable doc --open

  doc-private-open:
    desc: Generates documentation and opens in browser
    cmds:
      - cmd: cargo +stable doc --open --document-private-items

  fmt:
    desc: Runs code formatter
    cmds:
      - cmd: cargo +nightly fmt

  test:
    desc: Runs tests in debug mode
    cmds:
      - cmd: cargo +stable test

  testn:
    desc: Runs tests in debug mode
    cmds:
      - cmd: cargo +stable nextest run
