version: '3'

silent: true

tasks:

  build:
    desc: Builds in debug mode
    cmds:
      - cmd: cargo build

  clean:
    desc: Cleans all targets
    cmds:
      - cmd: cargo clean
      - cmd: rm -rf ./manual/book

  clippy:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo clippy --all-targets

  cov:
    desc: Generates code coverage report in text format
    cmds:
      - cmd: cargo llvm-cov clean
      - cmd: cargo llvm-cov --no-cfg-coverage

  cov-html:
    desc: Generates code coverage report in HTML format
    cmds:
      - cmd: cargo llvm-cov clean
      - cmd: cargo llvm-cov --no-cfg-coverage --html --open

  cov-badge:
    desc: Generates the detailed code coverage badge
    cmds:
      - cmd: cargo llvm-cov clean
      - cmd: cargo llvm-cov --no-cfg-coverage --json --summary-only | coverio --collapse --tag cov-badge

  doc:
    desc: Generates documentation
    cmds:
      - cmd: cargo doc

  doc-private:
    desc: Generates documentation
    cmds:
      - cmd: cargo doc --document-private-items

  doc-open:
    desc: Generates documentation and opens in browser
    cmds:
      - cmd: cargo doc --open

  doc-private-open:
    desc: Generates documentation and opens in browser
    cmds:
      - cmd: cargo doc --open --document-private-items

  fmt:
    desc: Runs code formatter
    cmds:
      - cmd: cargo +nightly fmt

  manual:
    desc: Builds the manual from its markdown files
    cmds:
      - cmd: cd manual && mdbook build

  readme:
    desc: Regenerates README.md file
    cmds:
      - cmd: magg readme
      - task: cov-badge

  serve:
    desc: Serves the manual locally and rebuilds on changes
    silent: true
    ignore_error: true
    cmds:
      - cmd: cd manual && mdbook serve || true

  test:
    desc: Runs tests in debug mode
    cmds:
      - cmd: cargo test

  testn:
    desc: Runs tests in debug mode
    cmds:
      - cmd: cargo nextest run
